# Cloud Build configuration for Ruby RX App
steps:
  # Create Artifact Registry repository if it doesn't exist
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud artifacts repositories create ruby-rx-repo \
          --repository-format=docker \
          --location=$_REGION \
          --description="Ruby RX App Docker Repository" || echo "Repository already exists"

  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "$_REGION-docker.pkg.dev/$PROJECT_ID/ruby-rx-repo/ruby-rx-app:latest",
        "-t",
        "$_REGION-docker.pkg.dev/$PROJECT_ID/ruby-rx-repo/ruby-rx-app:$BUILD_ID",
        ".",
      ]

  # Push the Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "$_REGION-docker.pkg.dev/$PROJECT_ID/ruby-rx-repo/ruby-rx-app:latest",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "$_REGION-docker.pkg.dev/$PROJECT_ID/ruby-rx-repo/ruby-rx-app:$BUILD_ID",
      ]

  # Update the Cloud Run service YAML with the project ID and region
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        sed -i "s/PROJECT_ID/$PROJECT_ID/g" cloud-run-service.yaml
        sed -i "s/REGION/$_REGION/g" cloud-run-service.yaml
        sed -i "s/:latest/:$BUILD_ID/g" cloud-run-service.yaml

  # Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "services",
        "replace",
        "cloud-run-service.yaml",
        "--region=$_REGION",
      ]

# Specify images to be pushed to Artifact Registry
images:
  - "$_REGION-docker.pkg.dev/$PROJECT_ID/ruby-rx-repo/ruby-rx-app:latest"
  - "$_REGION-docker.pkg.dev/$PROJECT_ID/ruby-rx-repo/ruby-rx-app:$BUILD_ID"

# Build configuration
options:
  # Use CLOUD_LOGGING_ONLY to resolve the service account logging issue
  logging: CLOUD_LOGGING_ONLY
  # Set machine type for faster builds
  machineType: "E2_HIGHCPU_8"
  # Increase disk size for Docker builds
  diskSizeGb: 100

# Substitution variables
substitutions:
  _REGION: "us-central1"

# Build timeout (30 minutes)
timeout: "1800s"
