# Cloud Build configuration for Ruby RX App
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/ruby-rx-app:latest',
      '-t', 'gcr.io/$PROJECT_ID/ruby-rx-app:$BUILD_ID',
      '.'
    ]
    
  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ruby-rx-app:latest']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ruby-rx-app:$BUILD_ID']

  # Update the Cloud Run service YAML with the project ID and region
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i "s/PROJECT_ID/$PROJECT_ID/g" cloud-run-service.yaml
        sed -i "s/REGION/$_REGION/g" cloud-run-service.yaml
        sed -i "s/:latest/:$BUILD_ID/g" cloud-run-service.yaml

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'services', 'replace', 
      'cloud-run-service.yaml',
      '--region=$_REGION'
    ]

# Specify images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/ruby-rx-app:latest'
  - 'gcr.io/$PROJECT_ID/ruby-rx-app:$BUILD_ID'

# Build configuration
options:
  # Use CLOUD_LOGGING_ONLY to resolve the service account logging issue
  logging: CLOUD_LOGGING_ONLY
  # Set machine type for faster builds
  machineType: 'E2_HIGHCPU_8'
  # Increase disk size for Docker builds
  diskSizeGb: 100

# Substitution variables
substitutions:
  _REGION: 'us-central1'

# Build timeout (30 minutes)
timeout: '1800s'