#!/bin/bash

# Manual setup for Artifact Registry (run this as project owner/admin)
set -e

PROJECT_ID="ruby-477016"
REGION="us-central1"
REPO_NAME="ruby-rx-repo"

echo "🔧 Manual Artifact Registry Setup"
echo "Run these commands in Google Cloud Console or with proper admin permissions:"
echo ""
echo "# 1. Enable required APIs"
echo "gcloud services enable artifactregistry.googleapis.com --project=${PROJECT_ID}"
echo "gcloud services enable cloudbuild.googleapis.com --project=${PROJECT_ID}"
echo "gcloud services enable run.googleapis.com --project=${PROJECT_ID}"
echo ""
echo "# 2. Create Artifact Registry repository"
echo "gcloud artifacts repositories create ${REPO_NAME} \\"
echo "    --repository-format=docker \\"
echo "    --location=${REGION} \\"
echo "    --description=\"Ruby RX App Docker Repository\" \\"
echo "    --project=${PROJECT_ID}"
echo ""
echo "# 3. Grant permissions to Cloud Build service account"
echo "gcloud projects add-iam-policy-binding ${PROJECT_ID} \\"
echo "    --member='serviceAccount:235422546541-compute@developer.gserviceaccount.com' \\"
echo "    --role='roles/artifactregistry.writer'"
echo ""
echo "gcloud projects add-iam-policy-binding ${PROJECT_ID} \\"
echo "    --member='serviceAccount:235422546541-compute@developer.gserviceaccount.com' \\"
echo "    --role='roles/run.admin'"
echo ""
echo "gcloud projects add-iam-policy-binding ${PROJECT_ID} \\"
echo "    --member='serviceAccount:235422546541-compute@developer.gserviceaccount.com' \\"
echo "    --role='roles/storage.admin'"
echo ""
echo "# 4. After running the above commands, you can deploy with:"
echo "gcloud builds submit --config=cloudbuild-simple.yaml --project=${PROJECT_ID}"